### ISSUE TITLE
Missing documentation on jwstuser when using mnemonics()

### ISSUE THREAD

**Issue by evamariaa** [GalagaBits/JWST-FGS-Spelunker#25]
I get this warning every time I load spelunker:
`Warning: jwstuser is not installed. mnemonics() will not work.`

While jwstuser is not part of spelunker I wasn't able to find any information in the documentation and online. I assume this will be a very common warning message so I recommend adding some more details on that or link to the relevant pages. 

This issue was made as part of the review for openjournals/joss-reviews/issues/6202.

**Comment by taylorbell57** [comment]
FYI, this is related to #27

I recommend at least adding `jwstuser` as an optional installation dependency in the `setup.py` file so that one can do `pip install spelunker[jwstuser]` or something like that to install both together. However, if the additional burden of always installing `jwstuser` is fairly minimal, then I don't see why it couldn't just be one of your required dependencies to save most folks from getting that warning every single time they load the package (especially since such warnings can sometimes get repeated when using parallelization).

**Comment by GalagaBits** [comment]
Okay, I will add `git+https://github.com/spacetelescope/jwstuser.git` to the dependencies list

**Comment by GalagaBits** [comment]
@taylorbell57, I have tried added `jwstuser @ git+https://github.com/spacetelescope/jwstuser@main#egg=jwstuser` to `install_requires` in my `setup.py` file. However, I get the error 

```
ERROR    HTTPError: 400 Bad Request from                 
         https://upload.pypi.org/legacy/                 
         Invalid value for requires_dist. Error: Can't   
         have direct dependency: 'jwstuser @             
         git+https://github.com/spacetelescope/jwstuser@m
         ain#egg=jwstuser'  
```

when trying to upload to PyPI. I'm not sure if there's currently a way to add direct dependencies into PyPI right now

**Comment by GalagaBits** [comment]
For now, I have added extra documentation on the installation page guiding users to the `jwstuser` github per #27 for installation instructions.

**Comment by taylorbell57** [comment]
@GalagaBits, I took a look at your setup.py file, and I was able to get the following to work. Remove the `requires` line (not clear to me that is needed and it seems to be the source of some issues), remove the `import numpy` line (since this requires users to first manually install numpy which isn't required since numpy isn't used during setup), and then set the `install_requires` line to

```
install_requires=['numpy','scipy', 'pandas', 'jwst', 'astroquery', 'astropy','astroplan','matplotlib', 'ray', 'jwstuser@git+https://github.com/spacetelescope/jwstuser.git', 'wheel'],
```

**Comment by GalagaBits** [comment]
When I follow this, I still get the exact error

```
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.5/30.5 kB • 00:00 • 203.2 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.                                                                                         
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                                                
         Invalid value for requires_dist. Error: Can't have direct dependency: 'jwstuser @ git+https://github.com/spacetelescope/jwstuser.git' 
```

**Comment by GalagaBits** [comment]
I use the following lines to package the library if it helps: 

`python setup.py sdist bdist_wheel`

`twine upload --repository pypi dist/*`

**Comment by taylorbell57** [comment]
Here are the contents of the setup.py file that work for me with a fresh Python 3.10 environment:

```
import re
from setuptools import setup, Extension, find_packages

VERSIONFILE='src/_version.py'
verstrline = open(VERSIONFILE, "rt").read()
VSRE = r"^__version__ = ['\"]([^'\"]*)['\"]"
mo = re.search(VSRE, verstrline, re.M)
if mo:
    verstr = mo.group(1)
else:
    raise RuntimeError("Unable to find version string in %s." % (VERSIONFILE,))

setup(name='spelunker',
      version=verstr,
      description='spelunker: a library to extract guidestar data and observe technical and stellar events',
      url='https://github.com/GalagaBits/JWST-FGS-Spelunker',
      author='Derod Deal',
      author_email='dealderod@ufl.edu',
      license='MIT',
      packages=['spelunker'],
      package_dir={'spelunker': 'src'},
      install_requires=['numpy','scipy', 'pandas', 'jwst', 'astroquery', 'astropy','astroplan','matplotlib', 'ray', 'jwstuser@git+https://github.com/spacetelescope/jwstuser.git', 'wheel'],
      keywords='guidestars',
      python_requires='>=3.10,<3.12',
      zip_safe=False)
```

**Comment by taylorbell57** [comment]
Aha, it is because I used `pip install .` instead of `python setup.py install`. The pip install method is now the recommended method, while the python setup.py install method is an old and now discouraged way of installing python packages

**Comment by GalagaBits** [comment]
Ah, so if I use `pip install . sdist bdist_wheel`, it should work?

**Comment by taylorbell57** [comment]
I personally have never used sdist or bdist_wheel and haven't uploaded anything to pypi, so I recommend you experiment, but I think `pip install . sdist bdist_wheel` should work for your purposes

**Comment by taylorbell57** [comment]
@GalagaBits, I see that the jwstuser package is still not included in the setup.py file. Had you just forgotten about this GitHub issue or did my suggestion not work for you?

**Comment by GalagaBits** [comment]
@taylorbell57, I tried implementing all suggestions here, but I ran into the same error.

**Comment by taylorbell57** [comment]
Ah indeed, I just tried it myself and got the same error. After some searching around, I found an explanation in [PEP-0440](https://peps.python.org/pep-0440/#direct-references).

> Public index servers SHOULD NOT allow the use of direct references in uploaded distributions. Direct references are intended as a tool for software integrators rather than publishers.

**Comment by taylorbell57** [comment]
I guess you'll have to wait until `jwstuser` is uploaded to PyPI before you could include it. Thanks for letting me know - this is relevant to some of my own repos which I've yet to try to host on PyPI

**Comment by GalagaBits** [comment]
No problem!
