### ISSUE TITLE
Issue with astroquery when calling cycle 2 JWST proposals with spelunker.load

### ISSUE THREAD

**Issue by evamariaa** [GalagaBits/JWST-FGS-Spelunker#26]
I tried loading spelunker with some cycle 2 JWST proposal IDs (that have definitely been completed) like this:
`spk = spelunker.load(pid=4098, obs_num='13', visit='1', save=True)`

but it gives an error message:
```
WARNING: NoResultsWarning: Query returned no results. [astroquery.mast.discovery_portal]
2024-01-30 13:39:17,619 - stpipe - WARNING - NoResultsWarning: Query returned no results.
```
Was there a recent update that affected the newer JWST observations? 

This issue was made as part of the review for openjournals/joss-reviews/issues/6202

**Comment by GalagaBits** [comment]
I am not completely sure why that error occurs. I think this is a astroquery issue, but I need to look more into it to be sure. However, when I run it, the line does run and I am able to print out a timeseries using `spk.timeseries_binned_plot()`. Are you able to get the same result? 
![image](https://github.com/GalagaBits/JWST-FGS-Spelunker/assets/34511693/559614e6-d86d-4a1a-8738-7cea4f89ecf0)

**Comment by GalagaBits** [comment]
Thanks for the reply. I have to ask a few more question to investigate this issue, then I'll fix it to the best of my ability. 

- Does the error `WARNING: NoResultsWarning: Query returned no results. [astroquery.mast.discovery_portal]
2024-01-30 13:39:17,619 - stpipe - WARNING - NoResultsWarning: Query returned no results.` occur with every program ID in Cycle 2 data?

- Are you able to still access features like time series plots and arrays for each Cycle 2 proposal after the error occurs?

- Are there any other errors or issues with Spelunker after receiving the error?

Thank you for using Spelunker and again I will fix this to the best of my ability.

**Comment by GalagaBits** [comment]
@evamariaa I have submitted an issue to astroquery about this https://github.com/astropy/astroquery/issues/2972.

**Comment by GalagaBits** [comment]
@evamariaa, according to https://github.com/astropy/astroquery/issues/2972, the program ID 4098 and others with this error have not been executed for observations yet. Certain Cycle 1 observations also have this error as well, and that is also due to the observations not yet being executed. Let me know if there is any other questions!

**Comment by evamariaa** [comment]
It's true that not all observations in programme ID 4098 have been executed but the majority has and the one I queried for definitely has (that's why I do get the FGSS data). So does this mean none of the JWST programmes that have been fully completed will be able to use the astroquery part of spelunker?

**Comment by GalagaBits** [comment]
@evamariaa Yes! You can still use Spelunker without using any astroquery related functions from Spelunker. Once you have downloaded the FITS for the GS-FG guidestar data, you can use the `readfile` function to load in all files with a specified PID in the parameter of the function. You will get all the features of Spelunker without the astroquery Spelunker functions. The latest Spelunker installation v1.1.10 works the best and avoids some of the bugs I recently went through. You'll need to change into the directory with your FITS files and use 

```
import spelunker

spk = spelunker.load()

spk.readfile(pid=4098)

```

to get all of your guidestar data loaded into spelunker. You can also load data with selected visit and observation numbers with the respective parameters.

As for the astroquery functions not working properly, I don't know why it is not working properly yet, but I do know that Spelunker get a list of data products from MAST given a query criteria:

```
        matched_obs = Observations.query_criteria(
            obs_collection = 'JWST',
            proposal_id=str(pid),
        )

```.

All of the data products links is then read according to `matched_obs` if it is from JWST and if it is under your program id. I realize that this takes all of the data products and can be very slow. I have tried to make it faster by looking for parameters that could successfully query a smaller amount of data products. The data products list is read and filtered using the following snippet:

```
        data_products = [Observations.get_product_list(obs) for obs in matched_obs]
        data_products = vstack(data_products)

        products = Observations.filter_products(data_products,
                    productType=["AUXILIARY",],
                    extension="fits",
                    productSubGroupDescription = "GS-FG",
                    dataproduct_type='image'
        )

 ```
It is further filtered with astropy table masking according to your input parameters. After the table of data products links has been filtered to a new table (`productsx`), the actual FITS data is downloaded:

```
manifest = Observations.download_products(productsx, download_dir=self.directory)
```

Let me know if you have any comments to this by pinging me and I will answer to the best of my ability

**Comment by evamariaa** [comment]
Ah I see, that's great thank you! That makes sense then and is good that it is explained here now so that anyone else who runs into this issue also can have a look!
