### ISSUE TITLE
Feedback on docs/user/fgs-spelunker_quickstart.rst

### ISSUE THREAD

**Issue by taylorbell57** [GalagaBits/JWST-FGS-Spelunker#33]
Below is some feedback on your `docs/user/fgs-spelunker_quickstart.rst` documentation page. I've made this a check list so that it's easy for me to cross things off after you've made some updates.

I'll also note that this notebook is particularly useful in explaining many of the detailed operations of the code. You likely want to make this more enticing for people to click and read rather than just calling it "Spelunker Guidestar Tools" which doesn't make it seem as useful as it is as a more in-depth tutorial. Putting this right below the Quickstart would likely also help convince new users to check it out - this far down the list, I thought it'd be some random extra utilities.

- [x] #40
- [x] `Currently, ``spk.readfile()`` does not support the folling
attributes: - ``fg_table``, - ``object_properties``.` Is this a comment meant to be noted outside of the code environment, or is this a warning message that is being output by the code? (I presume the former)
- [x] `"Current supported mnemonics: SA_ZHGAUPST (high-gain antenna), INIS_FWMTRCURR (NIRISS Filter Wheel Motor Current)"`. What barriers are there to accessing additional (arbitrary) mnemonics? It'd be amazing if folks could request any random mnemonic and get a result (I know there'd be several that I'd like to experiment with), but I also understand that you don't want to always grab all mnemonics since that'd be very wasteful.
- [x] `https://jwst-fgs-spelunker.readthedocs.io/en/latest/_images/fgs-spelunker_quickstart_51_1.png` Would it be possible to make this a GIF for the purposes of the readthedocs page so that web users can see what this animation looks like?

This issue was made as part of the review for https://github.com/openjournals/joss-reviews/issues/6202

**Comment by taylorbell57** [comment]
Additionally, running through the notebook myself results in different numerical results (and they are consistently different, so it's not just being caused by different random number seeds or whatever). I've attached my completed notebook (zipped so GitHub doesn't complain) so you can see that its results differ from those in your uploaded notebook at `notebooks/fgs-spelunker_quickstart.ipynb`.

[fgs-spelunker_quickstart_tjb.zip](https://github.com/GalagaBits/JWST-FGS-Spelunker/files/14132488/fgs-spelunker_quickstart_tjb.zip)

**Comment by GalagaBits** [comment]
For the third checklist, there is no barrier to access the mnemonics. However, there are thousands of different mnemonics to access and I was not completely sure if all of them will work with the `mnemonics` function. Users can input any mnemonics they want, but now going over it, should I give users the engineering telemetry list so they can experiment with different mnemonics themselves?

**Comment by GalagaBits** [comment]
Also, @taylorbell57, I have renamed the documentation page to 'Exploring Spelunker tools and features'.

**Comment by GalagaBits** [comment]
I accidently converted it into an issue and deleted it, but for the following comment

>  "The Program IDs that can be loaded are limited to programs without an exclusive access period or are available publicly." Is this still the case when using a MAST API token? If so, that's a really unfortunate limitation since it prohibits people from using the tool for their own data until the data become public (after which time most people will have already published their data). If not, then the ability to use MAST API tokens should be pointed out here.

I meant to say that if you do not have access to a MAST API token, you can only download and use publicly available Program IDs. However, with the `readfile` function, you can use fine guidance files you already have downloaded locally, and with the current version, with no drawbacks. If you do have a MAST API token, you can have access to any program under that token.

**Comment by GalagaBits** [comment]
> https://jwst-fgs-spelunker.readthedocs.io/en/latest/_images/fgs-spelunker_quickstart_51_1.png Would it be possible to make this a GIF for the purposes of the readthedocs page so that web users can see what this animation looks like?

Yes, I just fixed it!

**Comment by taylorbell57** [comment]
> I accidently converted it into an issue and deleted it, but for the following comment
> 
> > "The Program IDs that can be loaded are limited to programs without an exclusive access period or are available publicly." Is this still the case when using a MAST API token? If so, that's a really unfortunate limitation since it prohibits people from using the tool for their own data until the data become public (after which time most people will have already published their data). If not, then the ability to use MAST API tokens should be pointed out here.
> 
> I meant to say that if you do not have access to a MAST API token, you can only download and use publicly available Program IDs. However, with the `readfile` function, you can use fine guidance files you already have downloaded locally, and with the current version, with no drawbacks. If you do have a MAST API token, you will have access to any program under that token.

Good to know, that just needs to be clearer in the documentation then (which you may have now done - I haven't looked over any of the updates you've made yet)

**Comment by taylorbell57** [comment]
> For the third checklist, there is no barrier to access the mnemonics. However, there are thousands of different mnemonics to access and I was not completely sure if all of them will work with the `mnemonics` function. Users can input any mnemonics they want, but now going over it, should I give users the engineering telemetry list so they can experiment with different mnemonics themselves?

Gotcha, you should probably just add a note saying that other mnemonics may work but are not officially supported, and adding a link to a list of parameters or something like [this page](https://outerspace.stsci.edu/display/MASTDOCS/Engineering+Data#EngineeringData-Mnemonics) would be helpful
