### ISSUE TITLE
Malfunctioning Python Module Index on readthedocs

### ISSUE THREAD

**Issue by taylorbell57** [GalagaBits/JWST-FGS-Spelunker#34]
The "Python Module Index" found at https://jwst-fgs-spelunker.readthedocs.io/en/latest/py-modindex.html which is accessed through clicking on the MODULES link at the top of the readthedocs page only shows `spelunker`, and when you click on that it just takes you to https://jwst-fgs-spelunker.readthedocs.io/en/latest/optimizing_photometry.html#module-spelunker.

This issue was made as part of the review for https://github.com/openjournals/joss-reviews/issues/6202

**Comment by GalagaBits** [comment]
I have fixed this issue! I removed `optimizing_photometry` since the information was already provided in `API`.
