### ISSUE TITLE
gauss2d_fit TypeError: only length-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by mhooton** [GalagaBits/JWST-FGS-Spelunker#48]
Here's the error I'm getting when attempting to perform a Gaussian fit for a specific FGS dataset (it seems to work for other datasets). I'm using macOS 13.6.6, python 3.10.14 and spelunker 1.1.17

 32%|███▏      | 97909/308130 [00:57<02:50, 1232.69it/s](raylet) [2024-05-24 16:10:29,760 E 75152 10353252] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-05-24_16-08-56_941025_75129 is over 95% full, available space: 13070712832; capacity: 994662584320. Object creation will fail if spilling is required.
 35%|███▍      | 107579/308130 [01:05<02:02, 1631.54it/s]
Traceback (most recent call last):
  File "/Users/matthewhooton/PycharmProjects/spelunker/run.py", line 68, in <module>
    _ = spk.gauss2d_fit(ncpus=4)
  File "/Users/matthewhooton/anaconda3/envs/spelunker/lib/python3.10/site-packages/spelunker/spelunker.py", line 1250, in gauss2d_fit
    popt3 = ray.get(i)
  File "/Users/matthewhooton/anaconda3/envs/spelunker/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/Users/matthewhooton/anaconda3/envs/spelunker/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/matthewhooton/anaconda3/envs/spelunker/lib/python3.10/site-packages/ray/_private/worker.py", line 2623, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/Users/matthewhooton/anaconda3/envs/spelunker/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::fit_gaussian() (pid=75159, ip=127.0.0.1)
  File "/Users/matthewhooton/anaconda3/envs/spelunker/lib/python3.10/site-packages/spelunker/spelunker.py", line 1211, in fit_gaussian
    initial_guess[1], initial_guess[2] = int(coords[1]), int(coords[0])
TypeError: only length-1 arrays can be converted to Python scalars

**Comment by GalagaBits** [comment]
@mhooton Thank you for this issue! Which Program ID is this for? Is it a public one or a private dataset?

**Comment by nespinoza** [comment]
Hi @mhooton --- as per our conversations, this is a private dataset, so hard for me or @GalagaBits to debug in principle. Luckily, in this particular case the code snippet where this is crashing is pretty simple:

    datar = data.ravel()
    zodical_light = np.nanmedian(data[0:3,5:8])
    coords = np.where(data==datar.max())

    initial_guess[6] = zodical_light
    initial_guess[1], initial_guess[2] = int(coords[1]), int(coords[0])

My guess here is that the check in the third line of the snippet pasted above is giving back more than one pair of values, which makes the code to crash on the last line. I'm about to push a solution to this.

**Comment by nespinoza** [comment]
All right; @mhooton --- can you check the code works with the latest Github version in the `main` branch? To test:

- Uninstall spelunker `pip uninstall spelunker`.
- Clone the repository `git clone https://github.com/GalagaBits/JWST-FGS-Spelunker`.
- Get on the directory: `cd JWST-FGS-Spelunker`.
- Install latest `main` version of `spelunker` from that folder: `pip install .`. This should install version 1.1.18.
- Run your code snippet again.

Once we get confirmation from @mhooton that this works, @GalagaBits --- can you upload to `pip` (running `update.sh`) and make a new code release?

Thanks both!

- N.

**Comment by GalagaBits** [comment]
@nespinoza Yes! I can push the latest release to PyPI as soon as we get confirmation from @mhooton.

**Comment by nespinoza** [comment]
Awesome! The change I made actually takes care of two birds in one shot, because the `int` call made before was going to be deprecated in future versions too :).
